#ifndef PLASSEYLAB_PLAYGROUND_FIND_MINIMUM_TIME_TO_REACH_LAST_ROOM_H
#define PLASSEYLAB_PLAYGROUND_FIND_MINIMUM_TIME_TO_REACH_LAST_ROOM_H

int minTimeToReach(int **moveTime, int moveTimeSize, int *moveTimeColSize);

#endif // !PLASSEYLAB_PLAYGROUND_FIND_MINIMUM_TIME_TO_REACH_LAST_ROOM_H
