#ifndef PLASSEYLAB_PLAYGROUND_MINIMUM_DOMINO_ROTATIONS_H
#define PLASSEYLAB_PLAYGROUND_MINIMUM_DOMINO_ROTATIONS_H

int minDominoRotations(int *tops, int topsSize, int *bottoms, int bottomsSize);

#endif // !PLASSEYLAB_PLAYGROUND_MINIMUM_DOMINO_ROTATIONS_H
