#ifndef PLASSEYLAB_PLAYGROUND_COUNT_SUBARRAYS_H
#define PLASSEYLAB_PLAYGROUND_COUNT_SUBARRAYS_H

long long countSubarrays(int *nums, int numsSize, long long k);

#endif // !PLASSEYLAB_PLAYGROUND_COUNT_SUBARRAYS_H
